volumes:
    wordpress:
      name: wordpress
      driver: local
      driver_opts:
        device: /home/rayan/volumes/wordpress
        type: none
        o: bind
    mariadb:
      name: mariadb
      driver: local
      driver_opts:
        device: /home/rayan/volumes/mariadb
        type: none
        o: bind 
services:
    mariadb:
      build: ./requirements/mariadb
      image: mariadb
      container_name: mariadb
      networks:
        - inception
      env_file:
        - .env
      volumes:
        - mariadb:/var/lib/mysql
      init: true
    wordpress:
      build: ./requirements/wordpress
      image: wordpress
      container_name: wordpress
      networks:
        - inception
      env_file:
        - .env
      init: true
      depends_on:
        - mariadb
      volumes:
        - wordpress:/var/www/html
    nginx:
      build: ./requirements/nginx
      image: nginx
      container_name: nginx
      networks:
        - inception
      env_file:
        - .env
      ports:
        - "433:433"
      init: true
      depends_on:
        - wordpress
      volumes:
        - wordpress:/var/www/html
networks:
  inception:
    name: inception